/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { YieldForgeStaking__factory } from "./YieldForgeStaking__factory";
export { YieldForgeToken__factory } from "./YieldForgeToken__factory";
