/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { YieldForgeStaking } from "./YieldForgeStaking";
export type { YieldForgeToken } from "./YieldForgeToken";
