/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SampleCheck } from "./SampleCheck";
export * as factories from "./factories";
export { SampleCheck__factory } from "./factories/SampleCheck__factory";
